In [3]:
import itertools
import json
import os

import natsort
import pandas as pd

from seq2struct.utils import evaluation

In [8]:
os.chdir('..')

In [11]:
base = 'logdirs/20190201-hs-allmatches-anysplit'
results = []
for section, dirname, bs in itertools.product(
         ('val',), natsort.natsorted(os.listdir(base)), (1,)):
    try:
        metrics = evaluation.compute_metrics(
            'configs/hearthstone/nl2code.jsonnet', '', section, 
            os.path.join(base, dirname, 'infer-{}-step2600.jsonl'.format(section)))
    except IndexError:
        metrics = None
    if metrics is None:
        continue
    
    results.append((dirname.split('/')[-1], section, bs) + tuple(metrics.values()))

In [12]:
df = pd.DataFrame(results, columns=('Model', 'Section', 'Batch size', 'Exact match', 'Sentence BLEU', 'Corpus BLEU'))

In [13]:
# With objective using logsumexp of log probabilities (sum of probabilities) over the valid choices
df

,Model,Section,Batch size,Exact match,Sentence BLEU,Corpus BLEU
0,filt-contains-hole_st-cov-examples_nt-10,val,1,0.136364,0.782214,0.780884
1,filt-contains-hole_st-cov-examples_nt-20,val,1,0.106061,0.746259,0.740197
2,filt-contains-hole_st-cov-examples_nt-40,val,1,0.121212,0.766231,0.768039
3,filt-contains-hole_st-cov-examples_nt-80,val,1,0.090909,0.750347,0.746789
4,filt-contains-hole_st-cov-xent_nt-10,val,1,0.121212,0.767418,0.759678
5,filt-contains-hole_st-cov-xent_nt-20,val,1,0.121212,0.765257,0.778211
6,filt-contains-hole_st-cov-xent_nt-40,val,1,0.121212,0.767150,0.766655
7,filt-contains-hole_st-cov-xent_nt-80,val,1,0.136364,0.751691,0.741577
8,filt-none_st-cov-examples_nt-10,val,1,0.106061,0.763012,0.763896
9,filt-none_st-cov-examples_nt-20,val,1,0.106061,0.741796,0.765242
10,filt-none_st-cov-examples_nt-40,val,1,0.166667,0.770158,0.772183
11,filt-none_st-cov-examples_nt-80,val,1,0.136364,0.778386,0.774433
12,filt-none_st-cov-xent_nt-10,val,1,0.166667,0.770263,0.761363
13,filt-none_st-cov-xent_nt-20,val,1,0.106061,0.756485,0.739577
14,filt-none_st-cov-xent_nt-40,val,1,0.121212,0.758848,0.766763
15,filt-none_st-cov-xent_nt-80,val,1,0.106061,0.765201,0.777645

In [14]:
base = 'logdirs/20190201-hs-allmatches-anysplit-multimean'
results = []
for section, dirname, bs in itertools.product(
         ('val',), natsort.natsorted(os.listdir(base)), (1,)):
    try:
        metrics = evaluation.compute_metrics(
            'configs/hearthstone/nl2code.jsonnet', '', section, 
            os.path.join(base, dirname, 'infer-{}-step2600.jsonl'.format(section)))
    except IndexError:
        metrics = None
    if metrics is None:
        continue
    
    results.append((dirname.split('/')[-1], section, bs) + tuple(metrics.values()))

In [15]:
df = pd.DataFrame(results, columns=('Model', 'Section', 'Batch size', 'Exact match', 'Sentence BLEU', 'Corpus BLEU'))

In [16]:
# With objective using mean of log probabilities (geometric mean of probabilities) over the valid choices
df

,Model,Section,Batch size,Exact match,Sentence BLEU,Corpus BLEU
0,filt-contains-hole_st-cov-examples_nt-10,val,1,0.106061,0.751553,0.769558
1,filt-contains-hole_st-cov-examples_nt-20,val,1,0.090909,0.733184,0.731772
2,filt-contains-hole_st-cov-examples_nt-40,val,1,0.151515,0.761947,0.756905
3,filt-contains-hole_st-cov-examples_nt-80,val,1,0.106061,0.765872,0.772328
4,filt-contains-hole_st-cov-xent_nt-10,val,1,0.106061,0.747219,0.764024
5,filt-contains-hole_st-cov-xent_nt-20,val,1,0.121212,0.780949,0.773822
6,filt-contains-hole_st-cov-xent_nt-40,val,1,0.136364,0.765073,0.757530
7,filt-contains-hole_st-cov-xent_nt-80,val,1,0.151515,0.764711,0.762920
8,filt-none_st-cov-examples_nt-10,val,1,0.136364,0.766252,0.764879
9,filt-none_st-cov-examples_nt-20,val,1,0.151515,0.784208,0.761797
10,filt-none_st-cov-examples_nt-40,val,1,0.166667,0.790635,0.787137
11,filt-none_st-cov-examples_nt-80,val,1,0.090909,0.765000,0.767442
12,filt-none_st-cov-xent_nt-10,val,1,0.151515,0.749600,0.757408
13,filt-none_st-cov-xent_nt-20,val,1,0.136364,0.774357,0.765398
14,filt-none_st-cov-xent_nt-40,val,1,0.090909,0.754692,0.756321
15,filt-none_st-cov-xent_nt-80,val,1,0.121212,0.755776,0.766285